server:
  port: 8094
    
    
spring:
  application:
    name: apims2

  #cloud:
    #kubernetes:
     # discovery:
     #   enabled: true # to disable the DiscoveryClient
      #  all-namespaces: true
     #   include-external-name-services: true   # To enable the external Services [in kubernetes its spec.type:extername ->externaName: <your service name>]
      #  include-not-ready-addresses: true  # To discover service endpoint addresses that are not marked as "ready" by the kubernetes api server


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


info:
  app:
    name: apims2
    description: Api 2 SampleMS
    version: 1.0.0





# To disable Hystrix in Feign
feign:
  circuitbreaker:
    enabled: true

notification:
  service:
    url: http://localhost:8091


resilience4j:
  circuitbreaker:
    configs:
      notificationms:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 10
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true


management:
  health:
    circuitbreakers.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
      


endpoints:
  shutdown:
    enabled: true
    


logging:
  level:
    ROOT: DEBUG
    org:
      springframework:
        security: DEBUG



