server:
  port: 8091

spring:
  application:
    name: notificationms
#  #security:
#    #oauth2:
#      #resourceserver:
#        #jwt:
#          #issuer-uri: http://localhost:8080/auth/realm/sensfixrealm
#          #jwk-set-uri: http://localhost:8080/auth/realms/sensfixrealm/protocol/openid-connect/certs
#

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl:
    auto: update

# To disable Hystrix in Feign




eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ediscoveryms:8761/eureka/


info:
  app:
    name: notificationms
    description: notification Sample MS
    version: 1.0.0





# To disable Hystrix in Feign
feign:
  circuitbreaker:
    enabled: true

notification:
  service:
    url: http://localhost:8091


resilience4j:
  circuitbreaker:
    configs:
      notificationms:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 10
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true


management:
  health:
    circuitbreakers.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
      


endpoints:
  shutdown:
    enabled: true
    


logging:
  level:
    ROOT: DEBUG
    org:
      springframework:
        security: DEBUG



